openapi: 3.0.1
info:
  title: Audit Manager Service
  description: Rest Endpoints for operations related to audit
  license:
    name: Mosip
    url: https://docs.mosip.io/platform/license
  version: '1.0'
servers:
  - url: https://api-internal.collab.mosip.net/v1/auditmanager
    description: For Swagger
tags:
  - name: Audit manager controller
    description: Rest endpoints which consist of operations related to Audit Management
paths:
  /audits:
    post:
      tags:
        - Audit manager controller
      summary: Persist a audit
      description: persist a audit
      operationId: addAudit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestWrapperAuditRequestDto'
        required: true
      responses:
        '200':
          description: Success or you may find errors in error array in response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWrapperAuditResponseDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    AuditRequestDto:
      required:
        - actionTimeStamp
        - applicationId
        - applicationName
        - createdBy
        - eventId
        - eventName
        - eventType
        - hostIp
        - hostName
        - sessionUserId
      type: object
      properties:
        eventId:
          type: string
          minLength: 1
          maxLength: 64
          description: Unique identifier for the audit event.
        eventName:
          type: string
          minLength: 1
          maxLength: 128
          description: Descriptive name of the event (e.g., LOGIN, UPDATE_PROFILE).
        eventType:
          type: string
          minLength: 1
          maxLength: 64
          description: Type/category of the event (e.g., CREATE, UPDATE, DELETE).
        actionTimeStamp:
          type: string
          format: date-time
          description: Timestamp when the event occurred.
        hostName:
          type: string
          minLength: 1
          maxLength: 128
          description: Name of the machine or server where the event originated.
        hostIp:
          type: string
          minLength: 1
          maxLength: 256
          description: IP address of the machine that triggered the event.
        applicationId:
          type: string
          minLength: 1
          maxLength: 64
          description: Identifier of the application generating the audit.
        applicationName:
          type: string
          minLength: 1
          maxLength: 128
          description: Name of the application where the event occurred.
        sessionUserId:
          type: string
          minLength: 1
          maxLength: 256
          description: ID of the user who performed the action.
        sessionUserName:
          type: string
          minLength: 1
          maxLength: 128
          description: Username of the user who initiated the event.
        id:
          type: string
          minLength: 0
          maxLength: 64
          description: Optional unique identifier associated with the subject (e.g., UIN, VID).
        idType:
          type: string
          minLength: 0
          maxLength: 64
          description: Type of ID associated (e.g., UIN, VID, RID).
        createdBy:
          type: string
          minLength: 1
          maxLength: 256
          description: ID of the system or user who created the audit record.
        moduleName:
          type: string
          minLength: 0
          maxLength: 128
          description: Name of the module where the event occurred.
        moduleId:
          type: string
          minLength: 0
          maxLength: 64
          description: Optional ID of the module or component.
        description:
          type: string
          minLength: 0
          maxLength: 2048
          description: Detailed description or remarks for the event.
          
    RequestWrapperAuditRequestDto:
      required:
        - request
      type: object
      properties:
        id:
          type: string
          description: Identifier for the request, useful for tracking.
        version:
          type: string
          description: API version identifier.
        requesttime:
          type: string
          format: date-time
          description: Time when the request was initiated.
        metadata:
          type: object
          description: Additional metadata (e.g., locale, IP) associated with the request.
        request:
          $ref: '#/components/schemas/AuditRequestDto'
          description: Main payload for the audit request.

    AuditResponseDto:
      type: object
      properties:
        status:
          type: boolean
          description: Indicates whether the audit was saved successfully.

    ResponseWrapperAuditResponseDto:
      required:
        - response
      type: object
      properties:
        id:
          type: string
          description: Identifier for the response message.
        version:
          type: string
          description: API version identifier.
        responsetime:
          type: string
          format: date-time
          description: Timestamp of the response generation.
        metadata:
          type: object
          description: Metadata returned with the response.
        response:
          $ref: '#/components/schemas/AuditResponseDto'
          description: Contains success status of the audit persistence.
        errors:
          type: array
          description: List of any errors encountered during the operation.
          items:
            $ref: '#/components/schemas/ServiceError'

    ServiceError:
      type: object
      properties:
        errorCode:
          type: string
          description: Code representing the specific error.
        message:
          type: string
          description: Human-readable explanation of the error.
