-- -------------------------------------------------------------------------------------------------
-- Database Name: mosip_archive
-- Table Name 	: archive.
-- Purpose    	:   
-- Create By   	: Sadanandegowda
-- Created Date	: Dec-2020
-- 
-- Modified Date        Modified By         Comments / Remarks
-- ------------------------------------------------------------------------------------------
-- 
-- ------------------------------------------------------------------------------------------

-- object: archive.vid | type: TABLE --
-- DROP TABLE IF EXISTS archive.vid CASCADE;
CREATE TABLE archive.vid(
	id character varying(36) NOT NULL,
	vid character varying(36) NOT NULL,
	uin_hash character varying(128) NOT NULL,
	uin character varying(500) NOT NULL,
	vidtyp_code character varying(36) NOT NULL,
	generated_dtimes timestamp NOT NULL,
	expiry_dtimes timestamp,
	status_code character varying(32) NOT NULL,
	cr_by character varying(256) NOT NULL,
	cr_dtimes timestamp NOT NULL,
	upd_by character varying(256),
	upd_dtimes timestamp,
	is_deleted boolean,
	del_dtimes timestamp,
	CONSTRAINT pk_vid PRIMARY KEY (id),
	CONSTRAINT uk_vid UNIQUE (vid),
	CONSTRAINT uk_vid_uinhash UNIQUE (uin_hash,vidtyp_code,generated_dtimes)

);
-- ddl-end --
COMMENT ON TABLE archive.vid IS 'VID: To store generated list of Virtual IDs mapped to a UIN that can be used for Authentication. UIN of an individual should be secure, not to be disclosed publicly, so as part of security, VIDs are introduced. VIDs are timebound, can be changed, etc.';
-- ddl-end --
COMMENT ON COLUMN archive.vid.id IS 'ID: Unique id generated by the system for each of the virtual id generated';
-- ddl-end --
COMMENT ON COLUMN archive.vid.vid IS 'Virtual ID: Vertual Identification Number assigned to an individual, This vertual id can be used for individual authentication instead of using UIN';
-- ddl-end --
COMMENT ON COLUMN archive.vid.uin_hash IS 'UIN Hash: Unique Identification Number Hash: Hash value of Unique identification number assigned to individual.';
-- ddl-end --
COMMENT ON COLUMN archive.vid.uin IS 'UIN: Unique Identification Number : Unique identification number assigned to individual. Which is mapped to VID in idmap.';
-- ddl-end --
COMMENT ON COLUMN archive.vid.vidtyp_code IS 'Virtual ID Type: Type of an VID, Individual can have any VIDs which will used for multiple purposes. VID type can be perpetual ID, timebound ID..etc.';
-- ddl-end --
COMMENT ON COLUMN archive.vid.generated_dtimes IS 'Generated Date and Time: Date and timestamp when Vertual ID genereated.';
-- ddl-end --
COMMENT ON COLUMN archive.vid.expiry_dtimes IS 'Expiry Date and Time: Expiry Date and Time of the Vertual ID';
-- ddl-end --
COMMENT ON COLUMN archive.vid.status_code IS 'Status Code: Current Status code of the Virtual ID. Refers to master.status_list.code';
-- ddl-end --
COMMENT ON COLUMN archive.vid.cr_by IS 'Created By : ID or name of the user who create / insert record';
-- ddl-end --
COMMENT ON COLUMN archive.vid.cr_dtimes IS 'Created DateTimestamp : Date and Timestamp when the record is created/inserted';
-- ddl-end --
COMMENT ON COLUMN archive.vid.upd_by IS 'Updated By : ID or name of the user who update the record with new values';
-- ddl-end --
COMMENT ON COLUMN archive.vid.upd_dtimes IS 'Updated DateTimestamp : Date and Timestamp when any of the fields in the record is updated with new values.';
-- ddl-end --
COMMENT ON COLUMN archive.vid.is_deleted IS 'IS_Deleted : Flag to mark whether the record is Soft deleted.';
-- ddl-end --
COMMENT ON COLUMN archive.vid.del_dtimes IS 'Deleted DateTimestamp : Date and Timestamp when the record is soft deleted with is_deleted=TRUE';
-- ddl-end --
